const actionTypes = {
    GET_HOME: "GET_HOME",
    SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
    //music
    PLAY: 'PLAY',
    SET_ALBUM: 'SET_ALBUM',
    PLAYLIST: 'PLAYLIST',
    SKIP: 'SKIP',
    GET_NEW_RELEASE: 'GET_NEW_RELEASE',
    GET_TOP_10: 'GET_TOP_10',
    SET_PRE_SONGS: 'SET_PRE_SONGS',
    GET_CHART: 'GET_CHART',
    GET_ARTIST: 'GET_ARTIST',
    GET_COMPOSER: 'GET_COMPOSER',
    GET_ALL_SONG: 'GET_ALL_SONG',
    GET_ALL_PLAYLIST_NAMES: 'GET_ALL_PLAYLIST_NAMES',
}

export default actionTypes